export const SOCIAL_ROUTES = {
    followingFeed: '/api/social/feed',
    discoverFeed: '/api/social/discover',
    feed: '/api/social/feed',
    userPosts: (targetUserId: string) => `/api/social/users/${targetUserId}/posts`,
    posts: '/api/social/posts',
    post: (postId: string) => `/api/social/posts/${postId}`,
    postLikes: (postId: string) => `/api/social/posts/${postId}/likes`,
    postSaved: (postId: string) => `/api/social/posts/${postId}/saved`,
    savedPosts: '/api/social/saved-posts',
    comments: (postId: string) => `/api/social/posts/${postId}/comments`,
    comment: (postId: string, commentId: string) => `/api/social/posts/${postId}/comments/${commentId}`,
    commentReplies: (postId: string, commentId: string) =>
        `/api/social/posts/${postId}/comments/${commentId}/replies`,
    commentLikes: (postId: string, commentId: string) =>
        `/api/social/posts/${postId}/comments/${commentId}/likes`,
    socialUserSearch: '/api/social/users/search',
    socialUser: (userId: string) => `/api/social/users/${userId}`,
    followers: (userId: string) => `/api/social/users/${userId}/followers`,
    following: (userId: string) => `/api/social/users/${userId}/following`,
    followUser: (userId: string) => `/api/social/users/${userId}/follow`,
    followRequestsIncoming: '/api/social/follow-requests/incoming',
    followRequestsOutgoing: '/api/social/follow-requests/outgoing',
    followRequest: (requestId: string) => `/api/social/follow-requests/${requestId}`,
    workoutShares: '/api/social/workout-shares',
    myWorkoutShares: '/api/social/workout-shares/mine',
    goalShares: '/api/social/goal-shares',
    myGoalShares: '/api/social/goal-shares/mine',
    publicGoals: (userId: string) => `/api/social/users/${userId}/goals`,
    publicGoalDetail: (userId: string, goalId: string) => `/api/social/users/${userId}/goals/${goalId}`,
    publicGoalPeriods: (userId: string) => `/api/social/users/${userId}/goal-periods`,
    publicWorkoutDetail: (userId: string, workoutId: string) => `/api/social/users/${userId}/workouts/${workoutId}`,
    publicBadges: (userId: string) => `/api/social/users/${userId}/badges`,
    publicFeaturedBadges: (userId: string) => `/api/social/users/${userId}/badges/featured`,
    publicFeaturedPersonalRecord: (userId: string) => `/api/social/users/${userId}/personal-records/featured`,
    publicChallengeResults: (userId: string) => `/api/social/users/${userId}/challenge-results`,
} as const;
