export const WORKOUT_ROUTES = {
    base: '/api/workout',
    byId: (workoutId: string) => `/api/workout/${workoutId}`,
    createGym: '/api/workout/gym',
    createRunning: '/api/workout/running',
    createCycling: '/api/workout/cycling',
    createSwimming: '/api/workout/swimming',
    createYoga: '/api/workout/yoga',
    finish: (workoutId: string) => `/api/workout/${workoutId}/finish`,
    pause: (workoutId: string) => `/api/workout/${workoutId}/pause`,
    resume: (workoutId: string) => `/api/workout/${workoutId}/resume`,
    abandon: (workoutId: string) => `/api/workout/${workoutId}/abandon`,
    restore: (workoutId: string) => `/api/workout/${workoutId}/restore`,
    activeSession: '/api/workout/sessions/active',
    history: '/api/workout/history',
    archived: '/api/workout/archived',
    summary: '/api/workout/summary',
    saveAsRoutine: (workoutId: string) => `/api/workout/${workoutId}/save-as-routine`,
    fromRoutine: (routineId: string) => `/api/workout/from-routine/${routineId}`,
    exerciseCategories: '/api/workout/exercise-categories',
    exercises: '/api/workout/exercises',
    routines: '/api/workout/routines',
    routineById: (routineId: string) => `/api/workout/routines/${routineId}`,
    personalRecords: '/api/workout/personal-records',
    featuredPersonalRecord: '/api/workout/personal-records/featured',
    gymExercises: (workoutId: string) => `/api/workout/gym/${workoutId}/exercises`,
    gymExercise: (workoutId: string, exerciseEntryId: string) => `/api/workout/gym/${workoutId}/exercises/${exerciseEntryId}`,
    gymExerciseOrder: (workoutId: string) => `/api/workout/gym/${workoutId}/exercises/order`,
    gymSets: (workoutId: string, exerciseEntryId: string) => `/api/workout/gym/${workoutId}/exercises/${exerciseEntryId}/sets`,
    gymSet: (workoutId: string, exerciseEntryId: string, setId: string) => `/api/workout/gym/${workoutId}/exercises/${exerciseEntryId}/sets/${setId}`,
    gymSetCompletion: (workoutId: string, exerciseEntryId: string, setId: string) => `/api/workout/gym/${workoutId}/exercises/${exerciseEntryId}/sets/${setId}/completion`,
    gymSetOrder: (workoutId: string, exerciseEntryId: string) => `/api/workout/gym/${workoutId}/exercises/${exerciseEntryId}/sets/order`,
} as const;
